### PR TITLE
ui,openflow: quick fix of portnames

### LINKED ISSUE #1497: ui, openflow: port names are no more displayed in openflow rules tables
#1441 relies on the use of a subgraph. But this subgraph does not contain all the information used by ruledetail (we use interface linked to ovsports because they have the number OfPort metadata.)

### PR DESCRIPTION
**Pull request by pierrecregut**
The rule filtering functionality relies on a pre-filtering of the
graph. It breaked the display of port names in OpenFlow tables.

closes #1497

### CODE REVIEW

File: statics/js/components/rule-detail.js [hunk 1]
```diff
@@ -683,10 +683,11 @@ Vue.component('rule-detail', {
           return undefined
         },
         getTargets: function(node) {
+          var nodeid = node.id ? node.id : node.ID;
```
Comment (sergeyglazyrindev-samsung) [inline statics/js/components/rule-detail.js]: could you please add here some mention // @todo, get rid of this line when we refactor default skydive layout.
Right now we need to keep in mind such differences between different node representation: backend returns data with ID property but on frontend level we use id property. This is a thing which should be optimized in future.

**Comment by pierrecregut** [comment]
This is a quick fix but I don't like the approach of passing a subgraph to rule-detail:

1. This is a sledgehammer to crack a nut.
2. It puts constraints on what rule-detail can do with the graph. 

Another problem is why on earth some fields (id, metadata) are lowercase and others are capitalized. My guess is that it is linked with the way the subgraph is handled.

**Comment by sergeyglazyrindev-samsung** [comment]
> This is a quick fix but I don't like the approach of passing a subgraph to rule-detail:
> 
> 1. This is a sledgehammer to crack a nut.
> 2. It puts constraints on what rule-detail can do with the graph.
> 
> Another problem is why on earth some fields (id, metadata) are lowercase and others are capitalized. My guess is that it is linked with the way the subgraph is handled.

Yeah, I know. I added temporary bridge to handle this problem in this changeset:
https://github.com/skydive-project/skydive/pull/1481
But we need to comment the lines which should be doublechecked later. When we fix these bad things.

**Comment by safchain** [comment]
So the current version may be not perfect, but at least we have a way to filter which was not there before. I think it brings a value for the user (except the bug OK). 
I don't see why using Subgraph doesn't make sense, it is there for that to get part of the graph according to filter. The only thing I see is we could use another websocket connection to really subscribe to a subgraph. But things are there to be improved.

**Comment by lebauce** [comment]
run skydive-cdd-overview-tests

**Comment by pierrecregut** [comment]
There is another functionality that is broken by the subgraph approach: port highlighting no longer works.
I will submit another small patch.
What I really do not like about the approach is that the graph should be our unique intermediate between ui components, more precisely between actions requests and rendering. If we followed that, having alternative rendering will be just a matter of registering the right callbacks at the right place in the model.
But a subgraph obtained as it is is by an ajax query is just inert data. It no longer carry local model information such as, is this element highlighted, focused, etc.

**Comment by pierrecregut** [comment]
"the graph" is the unique mutable data structure in which you can easily navigate between nodes and change their ui status. The idea of the gremlin filter is the right approach, but the result should only be an evolving set of rule UUID that are then used to filter the rule nodes really considered in BridgeLayout.extract and those nodes come from "the graph". @sergeyglazyrindev  The problem is not just a ducktyping problem, we want the real nodes in the subgraph if we are going to work with such structures. For the problem at hand, I don't think we neeed the subgraph. Followup in #1504

**Comment by sergeyglazyrindev-samsung** [comment]
Hello, I agree with subgraph (you removed it recently in another changeset), but again, it is about keeping field names consistent with backend. So, my fix still has a sense because then we we get rid of this graph in raw javascript and migrate it to typescript, I prefer to have a proper field names, etc, so, such code would be more easier to migrate to the typescript skydive implementation.
